### ISSUE TITLE
Unable to run setup/development/deployment steps in the README

### ISSUE THREAD

**Issue by cjqian** [jstimes/SnagTheFlag#1]
I'm running npm version 1.4.21 on Debian. 

Code output here:

```
cjqian@penguin:~/SnagTheFlag$ npm install
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.19.98-08076-g24ab33fb8e14
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/cjqian/SnagTheFlag
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/cjqian/SnagTheFlag/npm-debug.log
npm ERR! not ok code 0
cjqian@penguin:~/SnagTheFlag$ npm start

> snagtheflag@1.0.0 start /home/cjqian/SnagTheFlag
> webpack-dev-server --open --config webpack.dev.js

sh: 1: webpack-dev-server: not found

npm ERR! snagtheflag@1.0.0 start: `webpack-dev-server --open --config webpack.dev.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the snagtheflag@1.0.0 start script.
npm ERR! This is most likely a problem with the snagtheflag package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --open --config webpack.dev.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls snagtheflag
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.19.98-08076-g24ab33fb8e14
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/cjqian/SnagTheFlag
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

**Comment by jstimes** [comment]
Latest npm version is v6, node is at v14 ... I'm guessing that's the issue.

"npm WARN This failure might be due to the use of legacy binary "node""
